language: scala
sudo: required
dist: trusty

scala:
  - 2.11.11

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION allClean coverage allTest
  - sbt ++$TRAVIS_SCALA_VERSION allReport


after_success: bash <(curl -s https://codecov.io/bash)